//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDien
    {
        public int ID { get; set; }
        public string ThuocTinh { get; set; }
        public string GiaTri { get; set; }
        public string GiaTri1 { get; set; }
        public string GiaTri2 { get; set; }
        public Nullable<bool> sys_del { get; set; }
    }
}
