//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongNCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDongNCC()
        {
            this.ChiTietHopDongMuas = new HashSet<ChiTietHopDongMua>();
        }
    
        public int MaHD { get; set; }
        public string TenHD { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<System.DateTime> NgayKi { get; set; }
        public string ThoiHan { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<bool> TinhTrangGiaoHang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDongMua> ChiTietHopDongMuas { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
